import {
  faArrowRightToBracket,
  faBan,
  faBars,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCircleCheck,
  faCircleInfo,
  faClock,
  faCloudArrowUp,
  faCopy,
  faDice,
  faDownload,
  faEye,
  faFolderOpen,
  faGear,
  faHouse,
  faKey,
  faLayerGroup,
  faListCheck,
  faLock,
  faLockOpen,
  faMagnifyingGlass,
  faMinus,
  faMoon,
  faPaperPlane,
  faPen,
  faPlus,
  faPrint,
  faRightFromBracket,
  faRotateRight,
  faSun,
  faTriangleExclamation,
  faUserPlus,
  faUsers,
  faXmark,
  faEyeSlash,
  faFileLines,
  faHourglassHalf,
  faInbox,
  faLinkSlash,
  faLocationDot,
  faScroll,
  faUser,
  faUserShield,
  faCheckDouble,
} from '@fortawesome/free-solid-svg-icons';

/** Все иконки приложения. Новую иконку - сначала сюда, потом в шаблон. */
export const APP_ICONS = [
  faArrowRightToBracket, faBan, faBars, faCheck, faChevronDown, faChevronLeft, faChevronRight,
  faCircleCheck, faCircleInfo, faClock, faCloudArrowUp, faCopy, faDice, faDownload, faEye,
  faFolderOpen, faGear, faHouse, faKey, faLayerGroup, faListCheck, faLock, faLockOpen,
  faMagnifyingGlass, faMinus, faMoon, faPaperPlane, faPen, faPlus, faPrint, faRightFromBracket,
  faRotateRight, faSun, faTriangleExclamation, faUserPlus, faUsers, faXmark, faEyeSlash, faCheckDouble,
  faFileLines, faHourglassHalf, faInbox, faLinkSlash, faLocationDot, faScroll, faUser, faUserShield,
];
